version: 2

sources:
  - name: eac_report
    database: EAC_Report
    schema: dbo
    tables:
      - name: MaterialBudgetItem
      - name: MaterialBudgetItemGroup
      - name: EACDept
      - name: DeptPool
      - name: EAC_Groups

  - name: employee2
    database: Employee2
    schema: dbo
    tables:
      - name: tblEmployee
      - name: tblLocation
      - name: tblLocationType
      - name: tblRegion
      - name: tblDepartment
      - name: tblDivision 
      - name: tblEmpJobTitle
      - name: tblDeptGroup

  - name: fsi_issues2
    database: FSI_Issues2
    schema: dbo
    tables:
      - name: tblIssueObjectXref
      - name: tblClassLink
      - name: tblIssue
      - name: tblStatus
      - name: tblClassification
      - name: tblLostTimeType
      - name: tblPriority
      - name: tblPriorityType
      - name: tblIssueCategory
      - name: tblIssue_Trng_Category
      - name: tblCause
      - name: tblRootCauseType

  - name: project2
    database: Project2
    schema: dbo
    tables:
      - name: tblProject
      - name: tblStatus
      - name: tblProjType
      - name: tblAccountingType
      - name: tblProjPMXref

  - name: sim2
    database: Sim2
    schema: dbo
    tables:
      - name: tblACCircular
      - name: tblACModels
      - name: tblACModelType
      - name: tblCertAgency
      - name: tblCertification
      - name: tblCertLevel
      - name: tblClassLink
      - name: tblConfig
      - name: tblMfg
      - name: tblObjectHier
      - name: tblOwner
      - name: tblProjSimXref
      - name: tblSim
      - name: tblSimGroup
      - name: tblSimType
      - name: tblSimTypeGroup
      - name: tblStatus
      - name: tblSystems
