version: 2

sources:
  - name: logging
    database: SimulationsAnalyticsLogging
    schema: dbo
    tables:
      - name: DBTProcessExecutionLog
      - name: DBTExecutionLog
      - name: DBTExecutionParameterLog
      - name: StageTableLastUpdate
