version: 2

sources:
  - name: mart
    database: SimulationsAnalytics
    schema: dbo
    tables:
      - name: DimUser
      - name: DimProject
      - name: DimSimulator
      - name: DimSimulatorConfiguration
      - name: DimSimulatorQualification
      - name: DimCenter
